spring.application.name=gestionLicencias

spring.datasource.url=jdbc:mysql://hopper.proxy.rlwy.net:24223/railway

spring.datasource.username=root
spring.datasource.password=xNPwkRDJtjUJhnJbbvvgtHJiDbtMhmZf

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true